# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57bc9b74e948d4978cad3612135a8c329549617578798fdc7b6a07f2fc06d421851781bf46908815de262bfac4c1271d0c4249ea7582e209f86320a90422fe10

test:
  secret_key_base: fdb2a6ea5f444c426c90dee7aa8f7d5f0a1b51fe1b0d478243f319a464fc1ab30bd3bea9e8997d00f231cd6ae1db990268473bbb14bde8900743b2ba6fa0ba97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
